### PR TITLE
Proposal for ease of use extensions

### PR DESCRIPTION
**Pull request by dcdillon**
I took a first pass at creating an "easy to use" interface to psig.

Basically you instantiate a `signal_manager`.  When you call `init()` on it, you tell it what signals you want to capture and all signals are masked on the current thread.  When you call `exec()` on it, all signals are unmasked and the `sigwaitinfo()` loop is started.

It has two callbacks that can be registered with the call to `exec()`.  They are a signal handler and an exit handler.  The signal handler is called every time `sigwaitinfo()` returns a valid signal.  The exit handler is called when the `sigwaitinfo()` loop is exited.

This is just a proposal to get things started.  @cknite please take a look and let me know if you think it's a good start or if you have a different idea of how this can work.

An example is included in `examples/exit_on_any_signal.cpp`.

### CODE REVIEW

**Comment by dcdillon** [comment]
1) I'll try to think of a better name....perhaps `block_signals`
2) Will make that change shortly
3) Removed that call at 280
4) I have no religion...kill() is reasonable there...I'll change it to that
5) I stole most of it from Qt

**Comment by dcdillon** [comment]
OK.  Made the changes @cknite suggested.  Have a look now.

**Comment by dcdillon** [comment]
- Changed the definition of `kill()` to simply signal the process
- Added a `stop()` function that forces `exec()` to exit
- Changed the whole thing to a singleton with static calls for `block_signals()`, `exec()`, etc.

**Comment by dcdillon** [comment]
@cknite, since you're more familiar with `std::chrono` and clang, can you take a look at this and help me with why it fails?  https://travis-ci.org/cpppractitioners/psig/jobs/81585327?  Other than that, I think things look good.

**Comment by dcdillon** [comment]
Ok.  Fixed it.  I think we're ok now.

**Comment by cknite** [comment]
Awesome.

I'll take a look.

**Pull request merged**
